/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package RutasEntrega;

/**
 *
 * @author Luisk
 */
public class FrmRutaEntrega extends javax.swing.JInternalFrame {

    private ListaRutaEntrega listaRutaEntrega; 

    /**
     * Creates new form FrmRutaEntrega
     */
    public FrmRutaEntrega() {
        initComponents();
        this.txtCodigoRuta.setVisible(false);
        this.txtDescripcion.setVisible(false);
        this.txtListaDestino.setVisible(false);
        this.txtNombre.setVisible(false);
        
        listaRutaEntrega = new ListaRutaEntrega();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCodigoRuta = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtListaDestino = new javax.swing.JTextField();
        lblCodigoRuta = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtResultados = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigoRuta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCodigoRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoRutaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCodigoRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 120, 30));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, 40));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 130, 40));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 100, 100, 40));

        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 120, 30));

        txtDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 120, 30));

        txtListaDestino.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtListaDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtListaDestinoActionPerformed(evt);
            }
        });
        jPanel1.add(txtListaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 120, 30));

        lblCodigoRuta.setText("   Codigo de Ruta: ");
        lblCodigoRuta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblCodigoRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 110, 30));

        lblNombre.setText("         Nombre: ");
        lblNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 110, 30));

        lblDescripcion.setText("       Descripcion: ");
        lblDescripcion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 110, 30));

        lblDestino.setText("         Destino:");
        lblDestino.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(lblDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 110, 30));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 100, 40));

        jButton1.setText("Guardar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 100, 90, 40));
        jPanel1.add(txtResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 310, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoRutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoRutaActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       // Hacer visibles los JTextField cuando se presiona el botón 'Agregar'
    txtCodigoRuta.setVisible(true);
    txtNombre.setVisible(true);
    txtDescripcion.setVisible(true);
    txtListaDestino.setVisible(true);

    // Hacer visibles las etiquetas correspondientes
    lblCodigoRuta.setVisible(true);
    lblNombre.setVisible(true);
    lblDescripcion.setVisible(true);
    lblDestino.setVisible(true);

    // Obtener los datos ingresados por el usuario
    String codigoRuta = txtCodigoRuta.getText();
    String nombre = txtNombre.getText();
    String descripcion = txtDescripcion.getText();

    // Crear una nueva instancia de RutaEntrega
    RutaEntrega nuevaRuta = new RutaEntrega(codigoRuta, nombre, descripcion);

    // Usar la instancia para agregar la nueva ruta a la lista
    listaRutaEntrega.agregarRuta(nuevaRuta);

    // Mostrar la información de la ruta en el área de resultados o en un mensaje
    txtResultados.setText("Ruta agregada: " + nuevaRuta.toString());

    // Limpiar los campos de texto
    txtCodigoRuta.setText("");
    txtNombre.setText("");
    txtDescripcion.setText("");
    txtListaDestino.setText(""); 

    // hacer invisibles los campos de texto y etiquetas nuevamente (si uno quiere)
    txtCodigoRuta.setVisible(false);
    txtNombre.setVisible(false);
    txtDescripcion.setVisible(false);
    txtListaDestino.setVisible(false);

    lblCodigoRuta.setVisible(false);
    lblNombre.setVisible(false);
    lblDescripcion.setVisible(false);
    lblDestino.setVisible(false);
       
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtListaDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtListaDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtListaDestinoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCodigoRuta;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtCodigoRuta;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtListaDestino;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtResultados;
    // End of variables declaration//GEN-END:variables
}
